### SIGN UP
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Luiza",
    "email": "luiza@gmail.com",
    "password": "testing12345"
}

### LOGIN
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "matheus@gmail.com",
    "password": "testing123"
}

### GET OWN PROFILE
GET http://localhost:3003/users/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjEzOTQyMiwiZXhwIjoxNjc2MTQxMjIyfQ._sR1v9Q-arCftfOGAuhX-BkNLYO9q_RLfU5KHzp_AIQ

### GET OTHER USER PROFILE
GET http://localhost:3003/users/user/614a7174-6e53-48cd-8e62-e2d745f73ca9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjEzOTQyMiwiZXhwIjoxNjc2MTQxMjIyfQ._sR1v9Q-arCftfOGAuhX-BkNLYO9q_RLfU5KHzp_AIQ

### CREATE RECIPE
POST http://localhost:3003/recipes/recipe
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGE3MTc0LTZlNTMtNDhjZC04ZTYyLWUyZDc0NWY3M2NhOSIsImlhdCI6MTY3NjQxMTczNSwiZXhwIjoxNjc2NDE1MzM1fQ.VNIMiu69pU_7hS3TFuGCF90brIj9hu-FnP5J3PEzj6M
Content-Type: application/json

{
    "title": "Whey",
    "description": "Misture o pó de whey em água em temperatura ambiente."
}

### GET ALL RECIPES
GET http://localhost:3003/recipes/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjMzMDc1MCwiZXhwIjoxNjc2MzMyNTUwfQ.ahAJVv2znP7YvRhu69Grhda0W3MlWOHTUal_9FKcUmU

### GET RECIPE BY ID
GET http://localhost:3003/recipes/recipe/0ed3f0fa-ef6f-44d7-94e6-3fe0b45a5083
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjMzMDc1MCwiZXhwIjoxNjc2MzMyNTUwfQ.ahAJVv2znP7YvRhu69Grhda0W3MlWOHTUal_9FKcUmU

### FOLLOW
POST http://localhost:3003/users/user/ef2f14ef-7c44-4e47-9172-20e9bd3d67c1/follow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjQxMDczMCwiZXhwIjoxNjc2NDEyNTMwfQ.9YN-XF-zCQF8u3sm4IvLxCBs_nAOPvuMFkz8LIC2ZAs

### UNFOLLOW
DELETE http://localhost:3003/users/user/614a7174-6e53-48cd-8e62-e2d745f73ca9/unfollow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjQxMDczMCwiZXhwIjoxNjc2NDEyNTMwfQ.9YN-XF-zCQF8u3sm4IvLxCBs_nAOPvuMFkz8LIC2ZAs

### GET USER FEED
GET http://localhost:3003/recipes/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMmU2MWFiLTJiZGMtNDI1My1hOTUxLTUzMzliMDIwOGIxZSIsImlhdCI6MTY3NjQxMDczMCwiZXhwIjoxNjc2NDEyNTMwfQ.9YN-XF-zCQF8u3sm4IvLxCBs_nAOPvuMFkz8LIC2ZAs

### EDIT RECIPE
PATCH http://localhost:3003/recipes/recipe/e6d78367-6841-47e7-b807-4d2ea1ae9a28/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGE3MTc0LTZlNTMtNDhjZC04ZTYyLWUyZDc0NWY3M2NhOSIsImlhdCI6MTY3NjUwMTcyMCwiZXhwIjoxNjc2NTA1MzIwfQ.xZzo9ky1_9ymnPCowWOKMM0_OzzejixCle2TtmucEiE
Content-Type: application/json

{
    "title": "Whey Protein"
}